; ==============================================================================
; REQUIRED STEAM INFORMATION
; ==============================================================================

; To get your SteamAPIKey:
; Go to https://steamcommunity.com/dev
; Under "Obtaining an Steam Web API Key" Click " by filling out this form"

; To get your SteamID64:
; Open the Steam client or app, click your profile name in the top right corner, and select Account details.
; Your Steam ID 64 will show right under your profile name

[Variables]
SteamAPIKey=
SteamID64=

; Save the file changes and refresh Rainmeter when done

Check for updates: https://github.com/RRam2020/Advanced-Mini-Steam-Launcher
